### ISSUE TITLE
Wich firmware for Revvitrc 50A

### ISSUE THREAD

**Issue by mkfrcp** [neoxic/ESCape32-WiFi-Link#2]
Hello,

I've bought a Revvitrc 50 A ESC. I'm impressed by the performances of your firmware !
It works so good. 

Do you know which version of firmware is compatible with this ESC BRANDY because I want to upgrade mine ?

As I'm french, I want to translate the menus of the wifi link. I will let you know when this job will be done. 

Thks

**Comment by neoxic** [comment]
Thank you! This is the wrong repo for such questions though. Please feel free to hop into our discord server. There's a link in the wiki. As for the menus, I believe you could maintain a localized "ESCape32-WiFi-Link-FR" fork.

**Comment by neoxic** [comment]
Or I could think of a language selector as a general approach to localization.

**Comment by mkfrcp** [comment]
Thks for you reply. From now, I'll try to use Discord 😊

Please let me me know if you decide to create a langage selector (it could
be of interest for many people).

Conv.

Le mer. 30 oct. 2024, 21:09, Arseny Vakhrushev ***@***.***> a
écrit :
